package crdprojectcalicoorg


// Optional BGP password for the peerings generated by this BGPPeer resource.
type BgpPeerSpecPassword struct {
	// Selects a key of a secret in the node pod's namespace.
	SecretKeyRef *BgpPeerSpecPasswordSecretKeyRef `field:"optional" json:"secretKeyRef" yaml:"secretKeyRef"`
}

