package crdprojectcalicoorg


// BGPPeerSpec contains the specification for a BGPPeer resource.
type BgpPeerSpec struct {
	// The AS Number of the peer.
	AsNumber *float64 `field:"optional" json:"asNumber" yaml:"asNumber"`
	// Option to keep the original nexthop field when routes are sent to a BGP Peer.
	//
	// Setting "true" configures the selected BGP Peers node to use the "next hop keep;" instead of "next hop self;"(default) in the specific branch of the Node on "bird.cfg".
	KeepOriginalNextHop *bool `field:"optional" json:"keepOriginalNextHop" yaml:"keepOriginalNextHop"`
	// Time to allow for software restart.
	//
	// When specified, this is configured as the graceful restart timeout.  When not specified, the BIRD default of 120s is used.
	MaxRestartTime *string `field:"optional" json:"maxRestartTime" yaml:"maxRestartTime"`
	// The node name identifying the Calico node instance that is targeted by this peer.
	//
	// If this is not set, and no nodeSelector is specified, then this BGP peer selects all nodes in the cluster.
	Node *string `field:"optional" json:"node" yaml:"node"`
	// Selector for the nodes that should have this peering.
	//
	// When this is set, the Node field must be empty.
	NodeSelector *string `field:"optional" json:"nodeSelector" yaml:"nodeSelector"`
	// Maximum number of local AS numbers that are allowed in the AS path for received routes.
	//
	// This removes BGP loop prevention and should only be used if absolutely necesssary.
	NumAllowedLocalAsNumbers *float64 `field:"optional" json:"numAllowedLocalAsNumbers" yaml:"numAllowedLocalAsNumbers"`
	// Optional BGP password for the peerings generated by this BGPPeer resource.
	Password *BgpPeerSpecPassword `field:"optional" json:"password" yaml:"password"`
	// The IP address of the peer followed by an optional port number to peer with.
	//
	// If port number is given, format should be `[<IPv6>]:port` or `<IPv4>:<port>` for IPv4. If optional port number is not set, and this peer IP and ASNumber belongs to a calico/node with ListenPort set in BGPConfiguration, then we use that port to peer.
	PeerIp *string `field:"optional" json:"peerIp" yaml:"peerIp"`
	// Selector for the remote nodes to peer with.
	//
	// When this is set, the PeerIP and ASNumber fields must be empty.  For each peering between the local node and selected remote nodes, we configure an IPv4 peering if both ends have NodeBGPSpec.IPv4Address specified, and an IPv6 peering if both ends have NodeBGPSpec.IPv6Address specified.  The remote AS number comes from the remote node's NodeBGPSpec.ASNumber, or the global default if that is not set.
	PeerSelector *string `field:"optional" json:"peerSelector" yaml:"peerSelector"`
	// Specifies whether and how to configure a source address for the peerings generated by this BGPPeer resource.
	//
	// Default value "UseNodeIP" means to configure the node IP as the source address.  "None" means not to configure a source address.
	SourceAddress *string `field:"optional" json:"sourceAddress" yaml:"sourceAddress"`
}

